name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            dist
            .vite
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json', 'src/**/*', 'index.html', 'vite.config.ts', 'tsconfig*.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Audit
        run: npm audit || true

      - name: Install
        run: npm ci

      - name: Outdated
        run: npm outdated || true

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Set package variables
        id: package
        run: |
          echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          PACKAGE_NAME="${{ steps.package.outputs.name }}"
          PACKAGE_VERSION="${{ steps.package.outputs.version }}"
          podman build -t $PACKAGE_NAME:$PACKAGE_VERSION .
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin
          podman tag $PACKAGE_NAME:$PACKAGE_VERSION ghcr.io/olddude/$PACKAGE_NAME:$PACKAGE_VERSION
          podman push ghcr.io/olddude/$PACKAGE_NAME:$PACKAGE_VERSION
